# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 内存参数 reserved-memory

- name: "【master-server】修改【内存参数】：master-server/conf/application.yaml"
  lineinfile:
    backup: yes
    path: "{{ dolphin_scheduler__install_media_upload }}/master-server/conf/application.yaml"
    regexp: '^\s\sreserved-memory'
    line: "  reserved-memory: {{ dolphin_scheduler__reserved_memory_gb }}"

- name: "【worker-server】修改【内存参数】：/worker-server/conf/application.yamlh"
  lineinfile:
    backup: yes
    path: "{{ dolphin_scheduler__install_media_upload }}/worker-server/conf/application.yaml"
    regexp: '^\s\sreserved-memory'
    line: "  reserved-memory: {{ dolphin_scheduler__reserved_memory_gb }}"

- name: "【alert-server】修改【内存参数】：alert-server/conf/application.yaml"
  lineinfile:
    backup: yes
    path: "{{ dolphin_scheduler__install_media_upload }}/alert-server/conf/application.yaml"
    regexp: '^\s\sreserved-memory'
    line: "  reserved-memory: {{ dolphin_scheduler__reserved_memory_gb }}"

- name: "【api-server】修改【内存参数】：/api-server/conf/application.yamlh"
  lineinfile:
    backup: yes
    path: "{{ dolphin_scheduler__install_media_upload }}/api-server/conf/application.yaml"
    regexp: '^\s\sreserved-memory'
    line: "  reserved-memory: {{ dolphin_scheduler__reserved_memory_gb }}"


# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 时区设置 / time-zone

- name: "【master-server】修改【时区】：master-server/conf/application.yaml"
  lineinfile:
    backup: yes
    path: "{{ dolphin_scheduler__install_media_upload }}/master-server/conf/application.yaml"
    regexp: '^\s\stime-zone'
    line: "  time-zone: {{ dolphin_scheduler__time_zone }}"

- name: "【worker-server】修改【时区】：/worker-server/conf/application.yamlh"
  lineinfile:
    backup: yes
    path: "{{ dolphin_scheduler__install_media_upload }}/worker-server/conf/application.yaml"
    regexp: '^\s\stime-zone'
    line: "  time-zone: {{ dolphin_scheduler__time_zone }}"

- name: "【alert-server】修改【时区】：alert-server/conf/application.yaml"
  lineinfile:
    backup: yes
    path: "{{ dolphin_scheduler__install_media_upload }}/alert-server/conf/application.yaml"
    regexp: '^\s\stime-zone'
    line: "  time-zone: {{ dolphin_scheduler__time_zone }}"

- name: "【api-server】修改【时区】：/api-server/conf/application.yamlh"
  lineinfile:
    backup: yes
    path: "{{ dolphin_scheduler__install_media_upload }}/api-server/conf/application.yaml"
    regexp: '^\s\stime-zone'
    line: "  time-zone: {{ dolphin_scheduler__time_zone }}"
